Add build action.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,9 +19,15 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Install
-        run: |
-          yarn install
-      
+        run: yarn install
+
+      - name: Test
+        run: yarn test
+
+      - name: Lint
+        # Split Lint into a separate task so that it can always run even if the tests fail.
+        run: yarn lint
+        if: success() || failure()
+
       - name: Build
-        run: |
-          yarn build chrome
+        run: yarn build chrome
